### ISSUE TITLE
Could not load class tl_user_vfu

### ISSUE THREAD

**Issue by lolwahn** [menatwork-ia/valumsFileUploader#54]
Erstmal Danke für die tolle Erweiterung!

Meine Kiste:

Debian 6.0.5
PHP Version 5.3.3-7+squeeze14

Folgendes Problem bei einen firsch aufgesetzen Contao 2.11.5 ohne Erweiterungen kommen folgenden Melddungen:

Bei  main.php?do=user

Fatal error: Could not load class tl_user_vfu in /Pfad zur Installation/system/functions.php on line 104
#0 [internal function]: __error(256, 'Could not load ...', '/Pfad zur Installation/t...', 104, Array)
#1 /Pfad zur Installation/system/functions.php(104): trigger_error('Could not load ...', 256)
#2 /Pfad zur Installation/system/modules/valumsFileUploader/dca/tl_user.php(61): __autoload('tl_user_vfu')
#3 /Pfad zur Installation/system/libraries/Controller.php(2812): include('/httpd/vhosts/t...')
#4 /Pfad zur Installation/system/modules/backend/Backend.php(194): Controller->loadDataContainer('tl_user')
#5 /Pfad zur Installation/contao/main.php(120): Backend->getBackendModule('user')
#6 /Pfad zur Installation/contao/main.php(230): Main->run()
#7 {main}

Notice: Undefined index: ORIG_PATH_INFO in /Pfad zur Installation/system/libraries/Environment.php on line 138 Notice: Undefined index: PATH_INFO in /Pfad zur Installation/system/libraries/Environment.php on line 138 Notice: Undefined index: ORIG_SCRIPT_NAME in /Pfad zur Installation/system/libraries/Environment.php on line 138 

Bei main.php?do=form&act=create

Fatal error: Could not load class tl_form_vfu in /Pfad zur Installation/system/functions.php on line 104
#0 [internal function]: __error(256, 'Could not load ...', '/Pfad zur Installation/t...', 104, Array)
#1 /Pfad zur Installation/system/functions.php(104): trigger_error('Could not load ...', 256)
#2 /Pfad zur Installation/system/modules/valumsFileUploader/dca/tl_form.php(32): __autoload('tl_form_vfu')
#3 /Pfad zur Installation/system/libraries/Controller.php(2812): include('/httpd/vhosts/t...')
#4 /Pfad zur Installation/system/modules/backend/Backend.php(194): Controller->loadDataContainer('tl_form')
#5 /Pfad zur Installation/contao/main.php(120): Backend->getBackendModule('form')
#6 /Pfad zur Installation/contao/main.php(230): Main->run()
#7 {main}

Notice: Undefined index: ORIG_PATH_INFO in /Pfad zur Installation/system/libraries/Environment.php on line 138 Notice: Undefined index: PATH_INFO in /Pfad zur Installation/system/libraries/Environment.php on line 138 Notice: Undefined index: ORIG_SCRIPT_NAME in /Pfad zur Installation/system/libraries/Environment.php on line 138 

Vermutlich wird es mehrere geben...

So das Witzige ist jetzt; wenn ich den Host auf PHP Version 5.2.17 umstelle dann funktioniert wieder alles... Habe den Host auch mit PHP Version 5.4.5 gestestet; da kommen die gleichen Meldungen.

**Comment by lolwahn** [comment]
Hallo,

ich habe das Problem bei mir gelöst.

ValumsFileUploader 3.1.0 stable build 9

In system/modules/valumsFileUploader/dca bei tl_user.php, tl_form.php und tl_files.php einfach jeweils die betreffende Klasse am Anfang vom Code stellen.

Getestet mit PHP Versionen 5.2.17,  5.3.3-7+squeeze14 und 5.4.5

Ich habe das Problem leider nicht reproduzieren können, da ich momentan nur einen Server zur Verfügung habe...
